	<div id="siteWrap">
	<div id="navElementparent">
	    <div id="navProper">
			<div class="oe_wrapper">
				<div id="whiteBg"></div>
				<ul id="oe_menu" class="oe_menu">
					<!-- -->
					<li>EXPLORATORIUM</li>
					<li><a href="">VISIT</a>
						<div  class="subNavFull">
							<ul>
								<li><h4>We're Moving</h4></li>
								<div id="subNavVisitDiv">
	In the Spring of 2013, the Epxloratorium is moving from the Palace of Fine Arts to Pier 15, on San Francisco's historic Embarcadero. Share the excitement with us at opening events, a special gala and pop-up exhibits in and around the Bay Area.							<ul>			<li><h4>NEW LOCATION</h4></li>
								<li><a href="#" story="story1">LOCATION, DIRECTIONS, & PARKING</a></li>
								<li><a href="#" story="story4">ACCESSIBILITY</a></li>
								<li><a href="#" story="story1">FAQ</a></li>
							
								<li><a href="#" story="story1">GUIA PARA VISITANTES</a></li>
								<li><a href="#" story="story1">參觀者指南</a></li></ul>
								</div>
							
							</ul>
							<ul>
								<li><h4>OPENING AT PIER 15</h4></li>
								<li><a href="#" story="story1">RSVP for Opening Gala</a></li>
								<li><a href="#" story="story1">Buy Tickets to After Party</a></li>
								<li><a href="#" story="story2">Become a Member</a></li>

								<li><h4>EXPLORE THE MUSEUM</h4></li>
								<li><a href="#" story="story3">Galleries</a></li>
								<li><a href="#" story="story2">Museum Map</a></li>
								<li><a href="#" story="story3">Calendar</a></li>
								<li><a href="#" story="story3">Film Screenings</a></li>
								<li><a href="#" story="story3">Tactile Dome</a></li>
								<li><a href="#" story="story3">Adult & Family Programs</a></li>

								<li><a href="#" story="story4">Where to Eat</a></li>
								<li><a href="#" story="story1">Museum Store</a></li>
								<li><a href="#" story="story3">Learning Commons</a></li>

								<li><a href="#" story="story2">School Visits</a></li>
								<li><a href="#" story="story3">Group Visits</a></li>
								<li><a href="#" story="story3">Event Rentals</a></li>
							</ul>
						
							<ul class="imageWell">
								<img src="images/story1.jpg" id="imageWell1"/>
							</ul>	
						</div>
					</li>
					<li><a href="">EXPLORE</a>
						<div  class="subNavFull"><!-- -112px -->
							<ul>
								<li><h4>Explore</h4></li>
							
								<div id="subNavExploreDiv">
									Some set up text could go here. I need to get some better images in and work out this nav. 
								
								
								
								
								</div>
							</ul>
						
							<ul>
								<li><h4>Explore by Topic</h4></li>
								<li ><a href="#">Astronomy & Space</a></li>
								<li><a href="#">Culture</a></li>
								<li><a href="#">Earth</a></li>
								<li><a href="#">Everyday Science</a></li>
								<li><a href="#">Human Body</a></li>
								<li><a href="#">Listening</a></li>
								<li><a href="#">Living Things</a></li>
								<li><a href="#">Material World</a></li>
								<li><a href="#">Mind</a></li>
								<li><a href="#">Seeing</a></li>
							</ul>
						
						
							<ul class="imageWell">
								<img src="images/place.jpg" id="imageWell1"/>
							</ul>	
						
				
						</div>
					</li>
				
					<li><a href="">EDUCATION</a>
						<div  class="subNavFull">
							<ul class="imageWell">
								<img src="images/place.jpg" id="imageWell1"/>
							</ul>	
							<ul>
														<li><h4>EDUCATION</h4></li>

														<li style="text-transform:none">

							The Exploratorium has three highly regarded professional development programs:</li>
						
							<br/>
								<li ><h4><a href="">FOR EDUCATORS</a></h4></li>
								<li>PROFESSIONAL PROGRAMS</li>
								<li><a href="#">- TEACHER INSTITUTE </a></li>
								<li><a href="#">- INSTITUTE FOR INQUIRY </a></li>
								<li><a href="#">- CENTER FOR INFORMAL LEARNING IN SCHOOLS</a></li>
								<li><a href="#">- CENTER FOR ART AND INQUIRY</a></li>
								<li><a href="#">- FIELD TRIP EXPLAINER PROGRAM</a></li>
								<li>TOOLS FOR TEACHING</li>
								<li><a href="#">- LEARNING COMMONS</a></li>
								<li><a href="#">- PUBLICATIONS</a></li>
							</ul>
							<ul>
								<li ><h4><a href="">FOR LEARNERS</a></h4></li>
								<li>YOUTH DEVELOPMENT PROGRAMS</li>
								<li><a href="#">- HIGH SCHOOL EXPLAINER PROGRAM</a></li>
								<li><a href="#">- XTECH</a></li>
								<li><a href="#">- COMMUNITY OUTREACH PROGRAM</a></li>
								<li>TOOLS FOR LEARNING</li>
								<li><a href="#">- WORKSHOPS, CLASSES & EXCURSIONS</a></li>
								<li><a href="#">- HOMESCHOOL PROGRAM</a></li>
								<li><a href="#">- HANDS-ON ACTIVITIES</a></li>
								<li><a href="#">- AFTERSCHOOL ACTIVITIES</a></li>
							<br/>
								<li><h4><a href="">LEARNING ABOUT LEARNING</a></h4></li>
								<li><a href="#">VISITOR RESEARCH & EVALUATION (VRE)</a></li>
								<li><a href="#">RELATING RESEARCH TO PRACTICE </a></li>
								<li><a href="#">CENTER FOR INFORMAL LEARNING IN SCHOOLS </a></li>
						
						
							</ul>
						</div>
					</li>
				
					<li><a href="">COLLABORATIONS</a>
						<div  class="subNavFull">
							<ul class="imageWell">
								<img src="images/place.jpg" id="imageWell1"/>
							</ul>	
							<ul>
							
								<li><h4<a href="">OUR GLOBAL REACH</a></h4></li>
								<li><a href="#">CENTER FOR INFORMAL LEARNING IN SCHOOLS</a></li>
								<li><a href="#">NETWORK FOR EXHIBIT-BASED TEACHING</a></li>
								<li><a href="#">GLOBAL STUDIOS</a></li>
								<li><a href="#">ONLINE ENGAGEMENT</a></li>
														
								<li><h4>OSHER FELLOWS</h4></li>
								<br/>
					
					
								<li><h3>PARTNERING WITH IMPACT</h3></li>
								 <li><h4><a href="">WITH SCIENCE AGENCIES</a></h4></li>
								<li><a href="#">- NATIONAL OCEANIC AND ATMOSTPHERIC ADMINISTRATION (NOAA)</a></li>
								<li><a href="#">- NASA</a></li>
						
								<li><h4><a href="">WITH EDUCATIONAL INSTITUTIONS</a></h4></li>
							
								<li><h4><a href="">WITH CORPORATE & CULTURAL LEADERS</a></h4></li>

							
						
							</ul>
							<ul>
								<li><h4>COLLABORATIONS</h4></li>

								<li style="text-transform:none">

							We thrive on opportunities to share our expertise and collaborate with leaders across the globe.  And we seek out amazing artists, scholars, authors, and scientists to bring to the museum every day.  </li>
								<br/>
								<li><h4>PARTNER WITH US</h4></li>
								<li><a href="#">BECOME A MEMBER</a></li>
								<li><a href="#">SUPPORT US</a></li>
								<li><a href="#">VOLUNTEER</a></li>

							
							</ul>
					
						</div>
					</li>
				

				

				

				

				

				

				

				

				

<!-- 				

				

					<li class="storeShove"><a href="">Stores</a>
						<div  class="subNavFull">
							<ul class="imageWell">
								<img src="images/store_well.jpg" id="imageWell1"/>
							</ul>	
							<ul>
								<li><h4>Something</h4></li>
								<li>BUY TICKETS</li>
								<li><a href="#">BUY MEMBERSHIPS</a></li>
								<li><a href="#">EXPLORE THE STORE</a></li>
								<li><a href="#">Berlin</a></li>
								<li><a href="#">London</a></li>
							</ul>
							<ul>
								<li><h4>SHOP BY CATEGORY</h4></li>
								<li><a href="#">Admission Tickets</a></li>
								<li><a href="#">Science Kits</a></li>
								<li><a href="#">Arts and Crafts</a></li>
								<li><a href="#">For the Younger Crowd</a></li>
								<li><a href="#">Magnets</a></li>
								<li><a href="#">For the Younger Crowd</a></li>
								<li><a href="#">Puzzles, Toys, and Games</a></li>
								<li><a href="#">Exploratorium Merchandise</a></li>
								<li><a href="#">Quirky and Fun</a></li>
								<li><a href="#">DVDs and Software</a></li>
								<li><a href="#">Books</a></li>
							</ul>
						
						</div>
					</li>
				 -->
				
				</ul>	
			</div>
       

	        <!-- The JavaScript -->
	        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
	        <script type="text/javascript">
	            $(function() {
					var $oe_menu		= $('#oe_menu');
					var $oe_menu_items	= $oe_menu.children('li');
					var $oe_overlay		= $('#oe_overlay');

	                $oe_menu_items.bind('mouseenter',function(){
						var $this = $(this);
						position = $(this).position();
						//alert(position.left)
						$('.subNavFull').css('opacity', 0)
						$('.subNavFull').css('left', function(index) {
						  return (-1 * position.left)-30 ;
						});
						$this.find('.subNavFull').css('opacity', 1)
					
						//alert(-1*position.left);
					
						$oe_menu_items.children('div').hide();
					
						$this.addClass('slided selected');
						$this.children('div:first').css('opacity', 0);
						$this.children('div').filter(":first").css('z-index','9999').stop(true,true).slideDown(100,function(){
							
						});
				
						$this.children('div').filter(":first").animate({
						    opacity: 1,
					   
						  }, 100, function() {
						    // Animation complete.
							$oe_menu_items.not('.slided').children('div').fadeOut();
							$this.removeClass('slided');
						
						  });
					
						$(".subNavFull li").hover(
						  function () {
							  testAttr = $(this).find("a").attr('story');
							  if(testAttr != undefined || "") {
							  		$("#imageWell1").attr("src", "images/" + testAttr + ".jpg");				
							  }
			
						  }, 
						  function () {
						    //$(this).find("span:last").remove();
						  }
						);
					
					
					}).bind('mouseleave',function(){
						var $this = $(this);
						$this.removeClass('selected').children('div').css('z-index','1');
					});

					$oe_menu.bind('mouseenter',function(){
						var $this = $(this);
					
						$oe_overlay.stop(true,true).fadeTo(200, 0.6);
						$this.addClass('hovered');
					}).bind('mouseleave',function(){
						var $this = $(this);
						$this.removeClass('hovered');
						$oe_overlay.stop(true,true).fadeTo(200, 0);
						$oe_menu_items.children('div').hide();
					})
				
				
				
				
	            });
	        </script>
	    
	    </div>
	</div>
	
	